### ISSUE TITLE
Is there any way to access getters outside of a vue component?

### ISSUE THREAD

**Issue by Waltarb** [mesqueeb/vuex-easy-access#24]
I would like to be able to get certain values from the store within my router where $store is not available so I need to import the store but then the getters seem to be unavailable.

**Comment by mesqueeb** [comment]
Thank you for your feature request!!
If you import your store it doesn’t have the getters?
Like so?

`import store from ./store.js
store.get()`

**Comment by mesqueeb** [comment]
@Waltarb Yeah, I checked, just make sure you initiate your Vuex store first
```
Vue.use(Vuex)
const store = new Vuex.Store(storeObject)
export store
```
afterwards the Vue router. There you can import store.

**Comment by Waltarb** [comment]
I do import it before the router but I still get `Property 'get' does not exist on type 'Store<{}>'.`

**Comment by Waltarb** [comment]
This is my index
```import Vue from 'vue';
import Vuetify from 'vuetify'
import App from './views/App.vue';
import store from './store/store'
import router from './config/router';
import 'vuetify/dist/vuetify.min.css'
import ApolloClient from "apollo-boost"
import VueApollo from "vue-apollo"

const apolloProvider = new VueApollo({
  defaultClient: new ApolloClient({
    uri: "http://localhost:3000/graphql"
  })
})

const el = document.createElement('div');
document.body.appendChild(el)

Vue.use(VueApollo)
Vue.use(Vuetify)

new Vue({
  el,
  store,
  router,
  apolloProvider,
  ...App
});
```

this is my store,
```import Vue from 'vue'
import Vuex from 'vuex'
import * as EasyAccess from 'vuex-easy-access';
import user from './modules/user'
const easyAccess = EasyAccess.createEasyAccess()


Vue.use(Vuex)

export default new Vuex.Store({
  plugins: [easyAccess],
  modules: {
    user
  }
})
```

and this is where I import it from the router

```import store from '../store/store'

Vue.use(Router)

const ifNotAuthenticated = async (to, from, next) => {
  const authenticated = await store.getters.user.isAuth;
```
This way with store.getters it works but that means I have to set anything the oldschool way which is indeed tedious.

**Comment by mesqueeb** [comment]
@Waltarb I don't see why you wouldn't be able to do 
```js
import store from '../../store/store'
```
inside your router file...?
Is it possible to share your project via zip or github? If not I'll try to manually recreate your structure.

**Comment by Waltarb** [comment]
Yeah the import it self works but then the functions from your plugin dont work, I need to rework the project if I want to share it because it has a lot of project specific stuff in it.

**Comment by Waltarb** [comment]
Updated the code examples since I messed up the markdown

**Comment by mesqueeb** [comment]
@Waltarb is your router imported in any other files besides your main.js file?

**Comment by Waltarb** [comment]
Nope

**Comment by mesqueeb** [comment]
inside your router file, are you sure it's not `'../../store/store'` instead of just one `../` ?

**Comment by Waltarb** [comment]
Yeah the path is correct since I can use the manually set getters, but I cant use the generated ones. Which is weird because I should have access to everything in the store object.

**Comment by mesqueeb** [comment]
@Waltarb Can you try this inside your store file ?

1. save the `new Vuex.Store` in a `const`
2. Check if get/set exists before your export.

```js
const store = new Vuex.Store(/*...*/)
console.log('check if setter exists', store.set)
console.log('check if getter exists', store.get)
export default store
```

**Comment by Waltarb** [comment]
Even there it gives an error damn. I will try and reproduce this in a blank project seems like something is going very wrong. I will give you an update!

**Comment by Waltarb** [comment]
Thanks for your time in advance

**Comment by mesqueeb** [comment]
@Waltarb I just looked again in my code, I'm not passing a default empty object as userConfig...
Try `createEasyAccess({})` instead of `createEasyAccess()`.

If this makes it work it's my fault... : P

**Comment by mesqueeb** [comment]
@Waltarb I have just updated the package to `3.0.3`.
It should work without passing anything in `createEasyAccess()` now.

You you please try:
```
npm i vuex-easy-access@latest
```
then
```js
import createEasyAccess from 'vuex-easy-access'
const easyAccess = createEasyAccess()
const store = new Vuex.Store(/*...*/)
console.log('check if setter exists', store.set)
console.log('check if getter exists', store.get)
export default store
```

**Comment by mesqueeb** [comment]
@Waltarb Let me know how it goes!!

**Comment by mesqueeb** [comment]
Feel free to open again if this didn’t solve your problem!

**Comment by mesqueeb** [comment]
@Waltarb did it work for you?

**Comment by YohannParis** [comment]
Lovely, just doing the following allowed me to access the store from outside Vue.js.
```
const store = new Vuex.Store(/*...*/)
export default store
```

**Comment by mesqueeb** [comment]
🎉 

<sub>--<br>Vuex Easy Access was made with ♥ by Luca Ban.<br>If you use this library in your projects, you can support the maintenance of this library by a small <a href="https://github.com/sponsors/mesqueeb">contribution via Github 💜</a>.<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>
