### ISSUE TITLE
typescript definition

### ISSUE THREAD

**Issue by joshua1** [mesqueeb/vuex-easy-access#30]
Hi @mesqueeb I am using this plugin in typescript based vue project and get the error 
```property 'set' does not exist on type 'Store<any>'```
same for get .
do you have a mini type definition file for get/set which seems like the injected method calls in vuex store object.

**Comment by joshua1** [comment]
Just saw the types folder. going through now

**Comment by joshua1** [comment]
I got around it with 
```
declare module 'vuex/types/index' {
  interface Store<S> {
    set: any
    get: any
    delete: any
  }
}
``` 
in a declaration file
if you have another way/option please drop it here .Thanks

**Comment by mesqueeb** [comment]
Dear @Joshua1 your setup is about right. I had not yet made an interface for the store after injection. I’ll add that asap and let you know here.

**Comment by mesqueeb** [comment]
@joshua1 Do you have any advice for me how to best do this?

Because as you can see [here in the index](https://github.com/mesqueeb/vuex-easy-access/blob/master/src/index.ts) the getter, setter and deletor are injected like so:
```js
store[conf.setter] = (path, payload) => { return defaultSetter(path, payload, store, conf) }
store[conf.getter] = (path) => { return defaultGetter(path, store) }
store[conf.deletor] = (path, payload) => { return defaultDeletor(path, payload, store, conf) }
```
I do not know what names the users pick, though it defaults to `get` `set` and `delete`.

**Comment by joshua1** [comment]
how about have defaultGetter defaultDeletor implement the vuex dispatch/commit interface or an interface that extends it. while the defaultGetter does the same thing for the vuex getter interface here https://github.com/vuejs/vuex/blob/dev/types/index.d.ts

**Comment by joshua1** [comment]
defaultMutations should be of type MutationTree<S> where S is the state. this is represented as .
```
export interface MutationTree<S> {
  [key: string]: Mutation<S>;
}
```
just my thought. or something similar

**Comment by joshua1** [comment]
better yet just have typescript  users create a declaration file with this entry 
```
declare module 'vuex/types/index' {
  interface Store<S> {
    set: any
    get: any
    delete: any
  }
}
```
setting "get", "set", "delete" to what ever they changed it to

**Comment by rob-64** [comment]
For the next guy...

```
import { Store } from "vuex";
declare module "vuex/types/index" {
  interface Store<S> {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    set(key: string, value: any);
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    get(key: string): any;
    delete(key: string);
  }
}

```

**Comment by mesqueeb** [comment]
@rob-64 how can I provide such a declaration file with my library?

**Comment by rob-64** [comment]
@mesqueeb 

Take a look at what vuex does for theirs: https://github.com/vuejs/vuex/blob/dev/types/vue.d.ts

You should be able to create a a similar file with my sample in types/vuex.d.ts for your repo.

Then look the vuex package.json, it has the following lines:

```
"typings": "types/index.d.ts",
"files": [
    "dist",
    "types/index.d.ts",
    "types/helpers.d.ts",
    "types/vue.d.ts"
  ],
```
